### PR TITLE
RF: Replace custom SafeConfigParserWithIncludes with standard ConfigParser

### PR DESCRIPTION
**Pull request by mih**
Companion of https://github.com/datalad/datalad/pull/5516 where it was
speculated whether the crawler even needs any of the custom
functionality that this class was providing.

### CODE REVIEW

**Comment by mih** [comment]
Tests seem to indicate that this class is no longer needed.

**Comment by yarikoptic** [comment]
Great, thank you @mih.  If any user reports breakage we would indeed just copy it into this codebase.

**Comment by yarikoptic** [comment]
uploaded 0.8.2 to pypi

**Comment by mih** [comment]
Speedy! Cool, thx!

**Pull request merged**
